### ISSUE TITLE
Bug import init multiprocessing

### ISSUE THREAD

**Issue by gschittek** [BaseAdresseNationale/api-gestion#318]
Lors de l'import d'un json de housenumbers provenant des données de l'IGN, l'API plante avec le message suivant : 
psycopg2.extensions.TransactionRollbackError: ERREUR:  Bloquage mortel détecté
DETAIL:  Le processus 57708 attend ShareLock sur transaction 68906379 ; bloqué par le processus 57710.
Le processus 57710 attend ShareLock sur transaction 68906454 ; bloqué par le processus 57708.
HINT:  Voir les journaux applicatifs du serveur pour les détails sur la requête.
CONTEXT:  lors de l'insertion de l'enregistrement (478, 34) de l'index dans la relation « housenumber_cia »

J'ai réussi à éviter le problème en lançant la commande avec l'option --workers 1 (merci Olivier), mais il faudrait corriger ce problème pour pouvoir paralléliser les taches et accélérer la commande

**Comment by yohanboniface** [comment]
Ennuyeux. Sur quelle machine? Ton poste perso ou un serveur de l'IGN?

Jamais reproduis ni en local ni sur les ex serveurs de préprod, où on lançait l'import sur 8 process.
Est-ce que tu peux passer ton terminal en anglais pour avoir les messages d'erreur dans cette langue, c'est plus facile pour enquêter ensuite, et faire des recherches.

`export LANG=en_US.UTF-8 && ban init…` devrait faire le boulot (peut-être `LANGUAGE=en_US.UTF-8` aussi, je sais jamais).

Aussi, copie-colle la stacktrace en entier.

Ça va pas être facile de corriger de mon côté sans reproduire le souci.

**Comment by gschittek** [comment]
Sur une machine de l'IGN que j'utilise via putty

(banenv)ban@HP1509W108-U:~/api-ban$ export LANG=en_US && export LANGUAGE=en_US.UTF-8 && ban import:init ~ban/banv1-shells/initEtalab/90/05_housenumbers.json
Processing /home/ban/banv1-shells/initEtalab/90/05_housenumbers.json
Computing file size
Done computing file size

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ban/api-ban/api-gestion/ban/commands/helpers.py", line 69, in collect_report
    results = func(*chunk)
  File "<decorator-gen-10>", line 2, in process_rows
  File "/home/ban/api-ban/api-gestion/ban/commands/helpers.py", line 199, in session
    return func(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/commands/init.py", line 46, in process_rows
    process_row(row)
  File "/home/ban/api-ban/api-gestion/ban/commands/init.py", line 59, in process_row
    return process_housenumber(row)
  File "/home/ban/api-ban/api-gestion/ban/commands/init.py", line 253, in process_housenumber
    validator.save()
  File "/home/ban/api-ban/api-gestion/ban/core/validators.py", line 146, in save
    self.instance = self.model.create(**data)
  File "/home/ban/api-ban/banenv/lib/python3.4/site-packages/peewee-2.10.1-py3.4.egg/peewee.py", line 4915, in create
    inst.save(force_insert=True)
  File "/home/ban/api-ban/api-gestion/ban/core/models.py", line 156, in save
    super().save(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/core/resource.py", line 74, in save
    return super().save(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/core/versioning.py", line 135, in save
    super().save(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/db/model.py", line 58, in save
    super().save(*args, **kwargs)
  File "/home/ban/api-ban/banenv/lib/python3.4/site-packages/peewee-2.10.1-py3.4.egg/peewee.py", line 5108, in save
    pk_from_cursor = self.insert(**field_dict).execute()
  File "/home/ban/api-ban/banenv/lib/python3.4/site-packages/peewee-2.10.1-py3.4.egg/peewee.py", line 3526, in execute
    cursor = self._execute()
  File "/home/ban/api-ban/banenv/lib/python3.4/site-packages/peewee-2.10.1-py3.4.egg/peewee.py", line 2912, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/home/ban/api-ban/banenv/lib/python3.4/site-packages/peewee-2.10.1-py3.4.egg/playhouse/postgres_ext.py", line 383, in execute_sql
    cursor.execute(sql, params or ())
psycopg2.extensions.TransactionRollbackError: ERREUR:  Bloquage mortel d\xe9tect\xe9
DETAIL:  Le processus 59108 attend ShareLock sur transaction 69226100 ; bloqu\xe9 par le processus 59113.
Le processus 59113 attend ShareLock sur transaction 69226132 ; bloqu\xe9 par le processus 59108.
HINT:  Voir les journaux applicatifs du serveur pour les d\xe9tails sur la requ\xeate.
CONTEXT:  lors de l'insertion de l'enregistrement (861, 13) de l'index dans la relation \xab housenumber_cia \xbb

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ban/api-ban/banenv/bin/ban", line 9, in <module>
    load_entry_point('ban==0.0.0', 'console_scripts', 'ban')()
  File "/home/ban/api-ban/api-gestion/ban/bin/__init__.py", line 9, in main
    args.func(args)
  File "/home/ban/api-ban/api-gestion/ban/commands/__init__.py", line 73, in invoke
    self(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/commands/__init__.py", line 45, in __call__
    self.command(*args, **kwargs)
  File "<decorator-gen-9>", line 2, in init
  File "/home/ban/api-ban/api-gestion/ban/commands/helpers.py", line 205, in nodiff
    res = func(*args, **kwargs)
  File "/home/ban/api-ban/api-gestion/ban/commands/init.py", line 39, in init
    all(helpers.batch(process_rows, rows, chunksize=100, total=total))
  File "/home/ban/api-ban/api-gestion/ban/commands/helpers.py", line 113, in batch
    for results, reports in pool.imap_unordered(func, iterable, chunksize):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 689, in next
    raise value
psycopg2.extensions.TransactionRollbackError: ERREUR:  Bloquage mortel d\xe9tect\xe9
DETAIL:  Le processus 59108 attend ShareLock sur transaction 69226100 ; bloqu\xe9 par le processus 59113.
Le processus 59113 attend ShareLock sur transaction 69226132 ; bloqu\xe9 par le processus 59108.
HINT:  Voir les journaux applicatifs du serveur pour les d\xe9tails sur la requ\xeate.
CONTEXT:  lors de l'insertion de l'enregistrement (861, 13) de l'index dans la relation \xab housenumber_cia \xbb

**Comment by ebuard** [comment]
Réglé
